spring:
  application:
    name: filemat-server

  datasource:
    url: jdbc:sqlite:/var/lib/filemat/filemat-server.db
    hikari:
      connection-init-sql: PRAGMA foreign_keys=ON;
    driver-class-name: org.sqlite.JDBC
  flyway:
    # Run flyway manually
    enabled: false

server:
  error:
    whitelabel:
      enabled: false